# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDF-ReportWriter
version:      1.0
version_from: lib/PDF/ReportWriter.pm
installdirs:  site
requires:
    Image::Size:                   2
    Number::Format:                0.1
    PDF::API2:                     0.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
